### ISSUE TITLE
loot file generation doesn't seem to work

### ISSUE THREAD

**Issue by shadoxxhd** [dmillerw/TooMuchLoot#3]
most generated loot files are completely empty and the other 2 have just one entry each.
EDIT: just looked in my log file, saw this: http://pastebin.com/wtzLsMd4

**Comment by GirafiStudios** [comment]
It's fixed here on Github. Just looks like that @dmillerw never did upload a new build of TooMuchLoot after he fixed it.

**Comment by shadoxxhd** [comment]
is there some sort of portable MCP w/ jdk you can use to easily compile mods on your own, or will i have to wait until he uploads a new version?

**Comment by dmillerw** [comment]
Doot doot, lemme get a build going and things updated!

**Comment by dmillerw** [comment]
http://minecraft.curseforge.com/projects/toomuchloot/files/2261887

Should be fixed now :)

**Comment by shadoxxhd** [comment]
sadly it's not fixed :(
same error as before

**Comment by GirafiStudios** [comment]
The loot files does generate when you create a new world (Possibly also when you join an existing world).

**Comment by shadoxxhd** [comment]
i tried to manually generate the files and the files were created, but completely empty (did not create new world; will try that next time i play)
